### ISSUE TITLE
no IMDosimetry value

### ISSUE THREAD

**Issue by liq07lzucn** [cerr/CERR#115]
https://github.com/cerr/CERR/blob/21fcfe81810865a95b3a653e74c7b2e54fce428a/IMRTP/recompDose/MC/generateDPMInfluence.m#L45

I have used CERR to import a set of dicom files which may be from eclipse or pinacle. But no IMDosimetry value here. It is blank, could you please tell me how to solve the problem?

**Comment by adityaapte** [comment]
The "Dosimetry" defined by the user shows up here. It is done via the IMRT --> IMRT Creation drop-down menu.
