### ISSUE TITLE
where is 'pbnum' from an to go?

### ISSUE THREAD

**Issue by liq07lzucn** [cerr/CERR#116]
https://github.com/cerr/CERR/blob/21fcfe81810865a95b3a653e74c7b2e54fce428a/IMRTP/recompDose/MC/generateDPMInfluence.m#L343

the pbnum is an unknown var, could you please explain?

**Comment by adityaapte** [comment]
It should be beamletCount instead of pbnum. I will push this to github. Thanks for pointing it out. 

- Aditya

**Comment by adityaapte** [comment]
Pushed the fix.
