### ISSUE TITLE
CERROptions.json support for MATLAB verion < 2016b

### ISSUE THREAD

**Issue by adityaapte** [cerr/CERR#169]

**Comment by ojalaj** [comment]
Any plans to work on this?

**Comment by adityaapte** [comment]
We are working on a fix and will update soon. Thanks!

**Comment by ojalaj** [comment]
Good to hear - great! Thanks!

**Comment by ojalaj** [comment]
Is this now fixed with some of the recent commits?

**Comment by ojalaj** [comment]
OK, thanks. I'll give it a try once I return back to the office after vacation (in 1½ weeks) and I'll let you know.

**Comment by ojalaj** [comment]
Hi.

CERR opens, Viewer opens, .mat file opens, but the there seems to be some problems/changes in the CT and dose colormaps? Do you recall any changes made to them after December 20 th 2017 (that was the branch I was previously using)?

**Comment by adityaapte** [comment]
There was indeed an issue with reading colormaps, but a fix was pushed on
Thursday last week. Can you please check if you have pulled updates since
then.

**Comment by ojalaj** [comment]
Yes, I pulled the latest master branch from July 19th....

**Comment by adityaapte** [comment]
Can you pull the latest one from today?

**Comment by ojalaj** [comment]
Yes, I pulled the latest one and did it again today (with 'from July 19th' I meant that the latest commits 5e516c9 and ee06a7f are dated July 19th). Anyhow, at least for me there are still problems with colormaps (I'm using Linux 64-bit, Matlab R2015a, Java 1.7.0_60).

**Comment by adityaapte** [comment]
Thanks for the info. We will investigate further.

**Comment by ojalaj** [comment]
With the master branch of CERR from 30th Aug there is (still) something wrong with colormaps. I'm using Matlab R2015a, Linux 64-bit. When plans are opened, the colormaps don't appear as they used to have in the past.
