### ISSUE TITLE
Error 'Reference to non-existent field 'planC' while loading mat file.

### ISSUE THREAD

**Issue by JunMa11** [cerr/CERR#173]
Dear CERR organisers,
Firstly, thanks for the excellent work!
When I load the mat file, the following error occurs:
```matlab
>> CERR
Working Directory: F:\MatlabTools\CERR\
CERR>>  Loading En_Roi.mat...
Warning: Variable 'planC' not found. 
> In sliceCallBack (line 1662) 
Reference to non-existent field 'planC'.
Error in sliceCallBack (line 1672)
        planC           = planC.planC; %Conversion from struct created by load 
Error while evaluating Menu Callback.
```

Would it be possible for you to tell me how to solve this problem?

Looking forward to your reply.
Best regards,
Edward

**Comment by EdwardMa12593** [comment]
@adityaapte Thanks for your quick reply.
My MATLAB version is `9.3.0.713579 (R2017b)` and CERR version is `5.2 (25-Jan-2017)`

**Comment by EdwardMa12593** [comment]
I also met some other mistakes。
- help error
![Markdown](http://i2.bvimg.com/595387/b795106c05e8af3e.png)
```
>> CERR
Working Directory: F:\MatlabTools\CERR\
Error using runCERRCommand (line 52)
Please load a plan first to use the command line help.
Error in sliceCallBack (line 3079)
            runCERRCommand; 
Error while evaluating UIControl Callback.
```

- first order stats error when I follow the tutorial [First-order-statistics](https://github.com/cerr/CERR/wiki/First-order-statistics)
![Markdown](http://i2.bvimg.com/595387/37c24d816fadbfd4.png)
```matlab
Error using discretize (line 75)
Second argument, edges, must have at least 2 elements.
Error in radiomics_first_order_stats (line 95)
quantizedV = discretize(Iarray+offsetForEnergy,edgeV) + eps;
Error in CERR_TestDemo (line 14)
statsFeatureS = radiomics_first_order_stats(planC,structNum,ctOffset); 
```

**Comment by adityaapte** [comment]
Thanks for the additional information. Here are few things to try out:

1> Pull the latest master branch from github: https://github.com/cerr/CERR
Note that CERR is hosted at https://github.com/cerr

2> The "help" command is available only after loading a plan in Viewer.

3> The radiomics_first_order_stats.m function requires an input argument
for the binWidth to calculate Entropy. Can you please provide an
appropriate value based on your scan type. I have updated the documentation
at https://github.com/cerr/CERR/wiki/First-order-statistics.

Please let me know in case you run into any issues.

Best,
Aditya
