### ISSUE TITLE
First step

### ISSUE THREAD

**Issue by Sophile** [cerr/CERR#175]
Could you tell me how to begin with these files? @rkpandya @cerr @rkpandya @adityaapte @nthakur34 @aditiiyer

**Comment by adityaapte** [comment]
You can start by pulling the latest CERR, adding all files/sub-folders to MATLAB path and importing DICOM. Is there something specific you are looking for?

**Comment by Sophile** [comment]
I want to know how to separate ROI from CT，any idea？ @adityaapte

**Comment by adityaapte** [comment]
Contouring tools might be helpful: https://github.com/cerr/CERR/wiki/Contouring-tools
