### ISSUE TITLE
The viewer is blank

### ISSUE THREAD

**Issue by Cohenyao** [cerr/CERR#197]
I downloaded the files on github, and uploaded the files into the Matlab 2014b. The software answered my command "CERR" , but after importing the DICOM files, there showed nothing when the viewer opened. And also, when I used Git bash to download the files, the feedback showed that _git@github.com: Permission denied (publickey)._ Waiting for someone's help.

**Comment by adityaapte** [comment]
Did you select the cerr file to open from the Viewer? File —> Open

For downloading from git bash, you can simply do the following:
git clone https://github.com/cerr/CERR
