### ISSUE TITLE
Display HU in matlab after convertion to matfile

### ISSUE THREAD

**Issue by dansmith8881234** [cerr/CERR#212]
I use CERR to convert a series of CT dicom images to one mat file. However, when I display an image in matlab it is not in HU units. Whatever conversion CERR is doing isn't going by HU=x(RescaleSlope)+RescaleIntercept either. Any thoughts?

**Comment by adityaapte** [comment]
Can you please elaborate more on the comparison? Any sample code showing how you obtained HUs from CERR? Note that the scanArray field in planC stores HU+CTOffset (which is typically 1000). This is done to store scanArray as unsigned integer.

**Comment by adityaapte** [comment]
Here is an example of obtaining HUs in CERR:
huM = double(planC{indexS.scan}(1).scanArray) -
planC{indexS.scan}(1).scanInfo(1).CTOffset;

Also, make sure that you are looking at the correct index between CERR and
Osirix. CERR's coordinate system is based on RTOG (
https://github.com/cerr/CERR/wiki/Coordinate-system) whereas Osirix is
DICOM-based.

**Comment by dansmith8881234** [comment]
I'm matching x,y positions and my values are still off. Others have suggested applying a linear attenuation conversion but that didn't seem to work either. How could I be reading the index wrong and how can I convert it? All help is very much appreciated.

 https://www.mathworks.com/matlabcentral/answers/430900-how-can-i-change-a-pixel-value-of-a-ct-image-series-to-display-hu?s_tid=mlc_ans_email_ques

**Comment by dansmith8881234** [comment]
I ran the code 
>> indexS = planC{end};
>> huM = double(planC{indexS.scan}(1).scanArray)-planC{indexS.scan}(1).scanInfo(1).CTOffset;
>> imagesc(huM(:,:,200))

and attached the image outputs, thanks!

[CT images.docx](https://github.com/cerr/CERR/files/2617229/CT.images.docx)

**Comment by adityaapte** [comment]
Thanks for the snapshots. Another option is to use the dicomread function
in MATLAB to read the slice values and compare.

**Comment by dansmith8881234** [comment]
thanks, but that gives me another new value at that position 2026. Nothing matches up.

**Comment by adityaapte** [comment]
Can you please verify this with the latest updates?
