### ISSUE TITLE
Problem with colormaps

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#215]
With the master branch of CERR from 30th Aug there is (still) something wrong with colormaps. I'm using Matlab R2015a, Linux 64-bit. When plans are opened, the colormaps don't appear as they used to have in the past.

**Comment by adityaapte** [comment]
Set colormap to starinterp in CERROptions.json

**Comment by ojalaj** [comment]
@adityaapte Thanks for the tip - it worked for HFS cases, but unfortunately it doesn't work for TBI cases with patient position HFDL - no matter what colormap I choose, dose is not visualized. If I move the slider for Scan-Dose to the "Dose" end, the CT image goes all black, only the contours are shown, and when sliding back towards the "Scan" end, the CT image gradually becomes visible. In the Dose Management window the dose is visualized though.

**Comment by adityaapte** [comment]
There might be an issue with importing HFDL dose. Can you provide us with sample DICOM?

**Comment by ojalaj** [comment]
Yes, I'll send you a link.
