### ISSUE TITLE
Problem with Importing DICOM Files

### ISSUE THREAD

**Issue by qaz719501894** [cerr/CERR#260]
(I'm a chinese user forgive my poor english)
When I try to Import a series of DICOM files I get this output and error massage.
java.io.IOException
	at sun.awt.image.GifImageDecoder.readHeader(GifImageDecoder.java:322)
	at sun.awt.image.GifImageDecoder.produceImage(GifImageDecoder.java:119)
	at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:269)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
 Reading header ... 
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.sponsorID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.protocolID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.subjectID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.submissionID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.timeSaved field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.lastSavedInVer field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.CERRImportVersion field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.anonymizedID field, leaving empty.
 Reading comment ... 
 Reading scan ... 
引用了不存在的字段 'Manufacturer'。

出错 populate_planC_field (line 127)
                        manufacturer = dataS(scansAdded+1).scanInfo(1).DICOMHeaders.Manufacturer;

出错 dcmdir2planC (line 48)
    cellData = populate_planC_field(cellNames{i}, dcmdir_PATIENT);

出错 CERRImportDCM4CHE (line 136)
    planC = dcmdir2planC(dcmdirS.(selected)); %wy

出错 CERR (line 168)
                    CERRImportDCM4CHE;
 
计算 UIControl Callback 时出错。

**Comment by YazdanGIT** [comment]
I have the same problem. is there anyone who can help me?
thanks
