### ISSUE TITLE
Problems with importing doses to TPS exported from CERR

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#318]
Hi.

CERR on Linux 64-bit Matlab 2015a.

On a CERR version with latest commits on January 12th 2019 I'm able to import doses with no problems to Eclipse TPS with following logs:
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connecting RT Dose Plan ''
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Find referenced Plan with UID '1.3.6.1.4.1.9590.100.1.2.61012269939301747631375481432774980004
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Not possible to connect RT Dose Plan to Plan, because referenced Plan '1.3.6.1.4.1.9590.100.1.2.61012269939301747631375481432774980004' is not present.
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Referenced Plan not found, RT Dose needs to be connected manually
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connecting Series ''
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Series Id is undefined and therefore set to 'Series'.
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connecting Study ''
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connecting to existing Study '1.2.392.200036.9116.2.5.1.37.2423319862.1545121240.195191'
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connecting Equipment ''
09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connecting to existing Equipment ''
09/24/2019 13:25:37                                                                                             Warning    Object Connection Not all objects in Series 1.3.6.1.4.1.9590.100.1.2.47436484828008536429756618513725423929 had same frame of reference.
Created for RTDose 1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522 new UID 1.2.246.352.210.5625353257116922947.5774602161586870658 and moved it to Series 1.2.246.352.210.5435162105578429931.8102462275774955691.

09/24/2019 13:25:37  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.192593327107799328330896487864130836522) Info       Object Connection Connection succeeded.

However, with most recent version of CERR, there are problems with UIDs and import to TPS doesn't work:
09/24/2019 08:42:11  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.153273849817239814429739665120251228035) Info       Object Connection Connecting RT Dose Plan ''
09/24/2019 08:42:11  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.153273849817239814429739665120251228035) Info       Object Connection Find referenced Plan with UID '1.3.6.1.4.1.9590.100.1.2.131094030940016587631722165983411991292
09/24/2019 08:42:11  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.153273849817239814429739665120251228035) Error      Object Connection Not possible to connect RT Dose Plan to Plan, because referenced Plan '1.3.6.1.4.1.9590.100.1.2.131094030940016587631722165983411991292' is not present and there are no plans suitable for connection.
09/24/2019 08:42:11  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.153273849817239814429739665120251228035) Error      Object Connection RT Dose cannot be imported, plan not found
09/24/2019 08:42:11  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.153273849817239814429739665120251228035) Error      Object Connection Copy of RT Dose Plan failed
09/24/2019 08:42:11  RT Dose: Plan - absolute (1.3.6.1.4.1.9590.100.1.2.153273849817239814429739665120251228035) Error      Object Connection Connection failed.

**Comment by ojalaj** [comment]
@adityaapte & @rkpandya  - have you found any reason for the problem above?

**Comment by ojalaj** [comment]
Any actions/solutions for this?

**Comment by adityaapte** [comment]
Looking in this. Thanks for notifying.

**Comment by ojalaj** [comment]
Thanks - let me know if you any further information from me!

**Comment by ojalaj** [comment]
I made the change suggested to CERROptions.json. To it have an effect, do I need to do something else than open MatLab.

I tried the export, but still got the same error, when importing to TPS. However, I did not re-import the original plan to CERR, from which I then made the export (of the MC-calculated dose distribution) for further import to TPS - I only tried the export.

**Comment by adityaapte** [comment]
I noticed that the original PatientID was not exported with the recent
updates (>May 2019). This has now been fixed. Can you please pull the
latest updates and try again? Thanks!

**Comment by ojalaj** [comment]
I pulled the latest updates.

I tried export from CERR and import to TPS with both retainOriginalUIDonExport" : "yes" and "no" (of course closing and re-opening MatLab after making the changes to CERROptions.json). However, unfortunately the problem is still there. Anything else I could try?
