### ISSUE TITLE
planC error message 

### ISSUE THREAD

**Issue by mms-14** [cerr/CERR#375]
When I try and use the command indexS=planC{end}; or run any script that uses it I receive the following error message : "Array indices must be positive integers or logical values." 
Is there something that may be causing this ?

**Comment by adityaapte** [comment]
Is planC already loaded in MATLAB? If it is open in CERR viewer, you can access planC by declaring it as a global variable. For example,

global planC
indexS = planC{end};

**Comment by mms-14** [comment]
I am trying to read in a 3ddose file into CERR, I've called dicomrt_read3ddose.m and then the commands :
global planC
indexS = planC{end};
which is where the error message is coming from

**Comment by adityaapte** [comment]
dicomrt_read3ddose.m reads dose from file. You need to add it to planC
along with CT scan. Here is a discussion on google group:
https://groups.google.com/forum/#!topic/cerr-forum/slQS_1j9gkg
