### ISSUE TITLE
Exported plan from TPS - problems with CERR-import and CERR-export

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#376]
Hi.

CERR on Linux 64-bit Matlab 2015a.

On a CERR version from January 12th 2019 I'm able to import a DICOM plan (CT, structure set, dose) from TPS to CERR with no problems, but with latest version from GitHub, I have following errors:

```
Error in scanfile_mldcm (line 46)
if ~exist('excludePixelDataFlag','var')

Output argument "attrData" (and maybe others) not assigned during call to "scanfile_mldcm".
Error in scandir_mldcm (line 82)
    [attrData, isDcm] = scanfile_mldcm(filename,excludePixelDataFlag);

Error in CERRImportDCM4CHE (line 87)
        patient = scandir_mldcm(fullfile(path, dirs(i).name), hWaitbar, i, excludePixelDataFlag);

Error in CERR (line 133)
                    CERRImportDCM4CHE;
 
Error while evaluating UIControl Callback
```

Also, when I try to export a previously imported plan with latest version from GitHub, I have following errors:

```
No method 'setFloat' with matching signature found for class 'org.dcm4che3.data.Attributes'.
Error in data2dcmElement (line 77)
        attr.setFloat(tag, vr, data);
Error in export_image_plane_module_field (line 91)
        el = data2dcmElement(template, data, tag);

Error in export_module (line 151)
   el = export_function(args);

Error in export_CT_IOD (line 116)
        imgplaneattr     = export_module('image_plane', 'scan', scanInfoS, scanS);

Error in export_planC_to_DICOM (line 60)
nNew     = export_CT_IOD(planC, filenameRoot, nWritten);

Error in CERRExportDICOM (line 185)
export_planC_to_DICOM(planC, destDir);
Error in CERR (line 110)
            CERRExportDICOM;
 
Error while evaluating UIControl Callback
```

**Comment by ojalaj** [comment]
Hi @adityaapte @aditiiyer - any ideas on this?

**Comment by ojalaj** [comment]
Hi @adityaapte  @aditiiyer - any ideas on this?

**Comment by adityaapte** [comment]
@ojalaj We have noticed similar behavior due to not enough Java Heap memory. Can you try increasing it? Also, MATLAB 2015a is not supported by CERR anymore (at least the Viewer part). Can you upgrade to a more recent version?

**Comment by ojalaj** [comment]
Hmm....OK, I think I have increased it already, but will try increasing more.

I haven't experienced that much problems with Viewer with CERR lately - when/in which commit was the compatibility to Matlab2015a get "broken"? Upgrading is not easy. Are there some workarounds for it? In what situations I may expect problems due to Matlab 2015a?

**Comment by adityaapte** [comment]
Changes pertain to Matlab's graphic engine , which got changed starting 2014b. So 2015a should be fine. I just haven't tested this version. Good to know that the Viewer works with 2015a.

Regarding import/export issue: have you tested on any other machine/Matlab version? If not, is it possible to test using the same dataset?

**Comment by ojalaj** [comment]
Thanks @adityaapte . Yeah, 2015a has been working fine with the Viewer for years.

I can the on other machine/Matlab version on Monday and let you know.

**Comment by ojalaj** [comment]
Hi @adityaapte . Tested on Win x64 Matlab 2017b, trying also increasing heap memory from 3GB to 5GB, but does not work - same errors. Do you want to try with the plan?

**Comment by ojalaj** [comment]
Hi @adityaapte  . Do you want to try with the plan?

**Comment by adityaapte** [comment]
Sure. Can you please provide the plan. Thanks.

**Comment by ojalaj** [comment]
Could you send me an upload link?

**Comment by ojalaj** [comment]
The plan has now been sent - thanks!

**Comment by ojalaj** [comment]
Have you had a chance to test this?

**Comment by adityaapte** [comment]
Looks like the RTSTRUCT file is corrupted. I was able to import without the RTSTRUCT file. Runnig MATLAB's "dicominfo" command produced the following warning: Warning: Not enough data imported... Do you see similar import issue with other datasets?

**Comment by ojalaj** [comment]
Hmm, need to check tomorrow, when I'm at the office. Anyhow, haven't experienced this with others. I could check importing some other plan using most recent CERR.

But, why on a CERR version from January 12th 2019 I'm able to import a DICOM plan (CT, structure set, dose) from TPS to CERR with no problems?

**Comment by ojalaj** [comment]
OK - some further debugging:
- CERR-Import issue: With the very latest branch of CERR I was able to import other DICOM-RT TPS plans that I have previously been able to import with earlier CERR branches. The problem seems to be only with that one plan. However, please note that I have been able to import the problematic plan with CERR version from January 12th 2019.

- CERR-Export issue: With the very latest branch of CERR I was not able to export any of the previously CERR-imported DICOM-RT TPS plans, resulting errors seen above. This also happened with such plan, which I, for debugging purposes, imported with the latest branch.

Might these two be separate issues?

**Comment by adityaapte** [comment]
Thanks for testing. Regarding DICOM export: we are working on fixing an issue with rtdose export.

**Comment by ojalaj** [comment]
@adityaapte Any new on this? Now I'm stuck on more than 1-year branch.

**Comment by ojalaj** [comment]
@adityaapte Any new on this?

**Comment by adityaapte** [comment]
I just pushed a few updates for RTDOSE export. We need to test more for different patient positions.  Please try out.

**Comment by ojalaj** [comment]
@adityaapte With CERR version from April 12th 2020, I successfully imported another plan from exported from Varian Eclipse TPS (having CT slices, RT structure set, RP plan file and RD dose files in the directory). Then I imported a Monte Carlo -calculated dose distribution with dose2cerr function and exported the whole plan (with "retainOriginalUIDonExport" : "yes"). Then I tried to import it back to Varian Eclipse TPS and the TPS recognized the CT slices and RT structure set as originals (i.e. all the required UIDs seem to be in place (?)), but no success with the dose file (error message "Not possible to connect RT Dose Plan to Plan, because referenced plan x.y.x...... is not present and there are no plans suitable for connection."). I believe there is something (still) wrong with UIDs. This workflow has worked in the past.

Have you any thoughts on this?

**Comment by ojalaj** [comment]
@adityaapte Could we somehow make progress with this - may I help somehow? Obviously some UIDs get lost/changed and/or metadata is missing for dose matrices on the way during the import and/or export and therefore the import back to TPS is not possible anymore. This might not have been a problem in the past, but in more recent versions of TPSs the requirements for data integrity have become stricter.

**Comment by adityaapte** [comment]
I will check whether the referenced plan UIDs are populated correctly. Do you import RTPLAN to CERR? The export routine is supposed to use this RTPLAN to assign UIDs to the exported RTDOSE.

**Comment by ojalaj** [comment]
@adityaapte Thanks for the reply. I usually have the RP file (RTPLAN) in the directory, but I need to check did I have it in this particular case, since I haven't known that it is used for something during the import. Good to know! Are the any commands I could use to check whether the UIDs in the imported plan match with the ones in RTPLAN file?

**Comment by ojalaj** [comment]
@adityaapte At least now the import to Eclipse TPS was successful (yes, I had the RP file in the directory, when importing to CERR) in terms of UID, at least partially - see below:

05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Not possible to connect RT Dose Plan to Plan, because referenced Plan 'YYYYY' is not present.
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Referenced Plan not found, RT Dose needs to be connected manually
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Connecting Series ''
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Series Id is undefined and therefore set to 'Series'.
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Connecting Study ''
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Connecting to existing Study 'YYYYY'
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Connecting Equipment ''
05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Connecting to existing Equipment ''
05/11/2020 10:01:51    Warning    Object Connection Not all objects in Series YYYYY had same frame of reference.
Created for RTDose YYYYY new UID YYYYYand moved it to Series YYYYY.

05/11/2020 10:01:51  RT Dose: Plan - absolute (XXXXX) Info       Object Connection Connection succeeded.

However, see also https://github.com/cerr/CERR/issues/448.

**Comment by ojalaj** [comment]
Fixed in https://github.com/cerr/CERR/commit/080935f56d5039fad2df9e8d47a95f1ee545cac9
