### ISSUE TITLE
DICOM Export from PlanC Specifically Dose Object (imageOrientation)

### ISSUE THREAD

**Issue by Elementboy575** [cerr/CERR#384]
I am just trying to export a DICOM plan that I had imported to CERR using either CERRExportDICOM or the export_planC_to_DICOM function, but run into this error either way:

```
Unrecognized function or variable 'scanInfoS'.

Error in export_image_plane_module_field (line 90)
        data = scanInfoS.imageOrientationPatient;

Error in export_module (line 151)
   el = export_function(args);

Error in export_RD_IOD (line 89)
    ssattr = export_module('image_plane', 'dose', doseS);

Error in export_planC_to_DICOM (line 68)
nNew     = export_RD_IOD(planC, filenameRoot, nWritten);
```

It seems to do with an issue in compiling the dose object, as it writes through the structure set to the output directory.  Any ideas or things to try would be greatly appreciated. MATLAB is not my forte.

**Comment by adityaapte** [comment]
We are looking into it. Thanks for reporting.
