### ISSUE TITLE
Index exceeds array bounds on DICOM files import 

### ISSUE THREAD

**Issue by Toni-SM** [cerr/CERR#389]
February, 2020 CERR version on MATLAB R2018a for Windows 

I can import some DICOM but with a lot of another DICOM files I get the next error on function sortStructures (…CERR\ML_Dicom\Import\sortStructures.m):

`Index exceeds array bounds.` 
`Error in sortStructures (line 56)`
`    if isObliqScanV(scanInd)  % strcmpi(modality,'mr')`
`Error in dcmdir2planC (line 398)`
`   planC{indexS.structures}(i) = sortStructures(planC{indexS.structures}(i),...`
`Error in CERRImportDCM4CHE (line 137)`
`   planC = dcmdir2planC(dcmdirS.(selected)); %wy`
`Error in CERR (line 133)`
`                   CERRImportDCM4CHE;`
`Error while evaluating UIControl Callback.`

This error happens because the _isObliqScanV_ array is empty. It is mandatory checks if the array is empty before index it. 

A proposal of solution is the next, on sortStructures function (…CERR\ML_Dicom\Import\sortStructures.m):
1)	Line 56:  `if ~isempty(isObliqScanV) && isObliqScanV(scanInd)`
2)	Also, line 65: `if isempty(locate_point) && ~isempty(isObliqScanV) && ~isObliqScanV(scanInd)`

**Comment by jim-rafferty** [comment]
I can confirm that @Toni-SM's solution works, at least for the data I've tried.

**Comment by adityaapte** [comment]
This has now been fixed in the dcmdir2planC.m file. It happened since
isObliqScanV was not set while importing RTSTRUCT/RTDOSE/RTPLAN objects
without the associated scan. Please pull the latest changes and try out.
