### ISSUE TITLE
Wavelets direction in radiomics calculation

### ISSUE THREAD

**Issue by duwang2015** [cerr/CERR#418]
Hi, I'm just trying to calculate the radiomics features for all Wavelets directions. 
The issue is if I define the direction in Json file as "All", the returned value will be like "Wavelets_Haar_All" instead of given all eight directions. 
If I put all eight directions in Json file as an array, the code will not process.
Any ideas or things to try would be greatly appreciated.

**Comment by adityaapte** [comment]
The "All" option is not supported. You will need to create a list of wavelet parameter dictionaries to specify different directions. For example, to calculate radiomics for HLH and HHH directions:

"imageType": {
  		  "Original": {},
		  "Wavelets": [{
				"Wavelets": "Haar",
				"Index": "",
				"Direction": "HLH"
			      },
             {
				"Wavelets": "Haar",
				"Index": "",
				"Direction": "HHH"
			      }]

	    },

**Comment by duwang2015** [comment]
Thank you for your comment, 
I did try that way, but it leads to another problem. Reading the Json file will return the Wavelets in paramS as a list like(Wavelets, Wavelets_1, Wavelet_2) which are invalid in the function "feval".

Error using feval
Undefined function or variable 'Wavelets_1'.
Error in processImage (line 322)
        outS.(filterType) = feval(filterType,scan3M,mask3M,paramS);

**Comment by adityaapte** [comment]
Can you please post your json file?

**Comment by duwang2015** [comment]
Never mind, I repeat one extra Wavelets setting. The problem is fixed now.
I appreciate you so much.
