### ISSUE TITLE
Dose downsampling?

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#419]
If I change in CERROptions.json and CERROptions.m (I'm not sure which would be enough) "downsampleLargeDoses" : "yes" to "no", why the imported doses (both DICOM and MC-based using dose2CERR) still seem to be downsampled?

**Comment by ojalaj** [comment]
@adityaapte Any comment on this?

**Comment by adityaapte** [comment]
"downsampleLargeDoses" is used only for RTOG files. It is not used during DICOM import. Can you check the size of dose distribution as follows:

global planC
indexS = planC{end};
doseNum = 1;
size(planC{indexS.dose}(doseNum).doseArray)

**Comment by ojalaj** [comment]
OK, great to know - couldn't guess this otherwise! So DICOM doses are exported as they were imported. Need to check once I return to the office.
