### ISSUE TITLE
Problem in longitudinal axis on DICOM export

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#448]
When importing a plan (CT, RP, RS, RD) from Eclipse TPS to CERR (from Apr 29th 2020) and importing an MC-calculated dose distribution (.3ddose from EGSnrc) using dose2CERR to the plan and exporting both dose distributions from CERR (TPS-calculated one and MC-calculated one) to be imported back to Eclipse TPS: 
a) There is nothing wrong in the TPS-calculated one, i.e., identical to the one originally in Eclipse
b) With the MC-calculated one the Z/longitudinal axis (cranio-caudal in HFS) is offset cranially ~30 cm. Doesn't seem to be related to coordinate sign (?), flipdims (?) etc. I also tried reverting the changes made to export_rt_dose_module_field.m on April 8th 2020. To me it seems to be just offset.

However, when doing the whole thing with CERR from January 12th 2019 everything is fine also with MC-calculated dose. Is there something not right on the Grid Frame Offset Vector given for the MC-calculated dose distribution (remember that all is good with the TPS-calculated dose).

**Comment by ojalaj** [comment]
Hi @adityaapte  - any comment on this?

**Comment by adityaapte** [comment]
We now store imagePatientPosition for dose from dicom header. I suspect this is not properly handled for MC dose. Can you point me to your script to import MC dose with an example dataset?

**Comment by ojalaj** [comment]
I have sent you the script via email. Do you need something else?

**Comment by ojalaj** [comment]
Fixed in https://github.com/cerr/CERR/commit/080935f56d5039fad2df9e8d47a95f1ee545cac9
