### ISSUE TITLE
DICOM import error 

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#460]
Hi.

I have a complete plan (CT, structures, dose) from Eclipse TPS imported to CERR.

I try to import another dose, but get following:

Error using populate_planC_field (line 308)
Not enough input arguments.
Error in insertDCMDose (line 50)
dataS = populate_planC_field('dose', dcmdirS.PATIENT); 
Error while evaluating Menu Callback

**Comment by ojalaj** [comment]
@adityaapte Any comment on this?

**Comment by adityaapte** [comment]
Just pushed a fix for it. Can you please pull the latest and try out.

**Comment by ojalaj** [comment]
@adityaapte Thanks for the quick fix! I'll try it once I return to the office. BTW, do you maintain an up-to-date CERR executable somewhere?

**Comment by ojalaj** [comment]
@adityaapte With the most recent branch of CERR, after re-importing the whole plan and then trying to import a separate dose, I still get following:

```
Undefined function 'fieldnames' for input arguments of type 'double'.
Error in dissimilarInsert (line 55)
newNames = fieldnames(newElement);

Error in insertDCMDose (line 58)
    planC{indexS.dose} = dissimilarInsert(planC{indexS.dose},dataS,length(planC{indexS.dose})+1); 
Error while evaluating Menu Callback
```

**Comment by ojalaj** [comment]
Hi @adityaapte  - have you any comment on this?

**Comment by adityaapte** [comment]
Looking into it.

**Comment by ojalaj** [comment]
@adityaapte Did you find anything on this?

**Comment by adityaapte** [comment]
I can reproduce this error if the dose file to be inserted contains modality other than RTDOSE. Can you please verify whether the dose file being  inserted is valid RTDOSE? Also, (not related to the error you are reporting) I pushed an update to initialize dcm4che3 classes in the insertDCMDose.m function in case they were not initialized before.

**Comment by ojalaj** [comment]
@adityaapte Yes the "Modality" tag in DICOM header is "RTDOSE". I'll check tomorrow whether the commit you made resolves the issue.

**Comment by ojalaj** [comment]
Seemed to work now (however I needed to make the change I reported in #473 ) - thanks for the help! I'll let you know, if I encounter some problematic cases.
