### ISSUE TITLE
What command can call CERR Extractor

### ISSUE THREAD

**Issue by LiHui1116** [cerr/CERR#476]
I've seen CERR Extractor in the page (https://github.com/cerr/CERR/wiki/CERR-Extractor:-Fusing-DVH-data-with-outcomes). But I don't know how to call this CERR Extractor. The page doesn't have any prompt.

**Comment by adityaapte** [comment]
There are couple of options:
1> On CERR startup GUI, under Review > Cohort
or 
2> type "structureNameMapGUI" in Matlab command window.
