### ISSUE TITLE
Trouble running CERR on R2020a, ubuntu 18.04

### ISSUE THREAD

**Issue by dominicrafferty** [cerr/CERR#488]
Hello,

I cannot get CERR to open any DICOM files.

When I launch CERR, I receive the following errors on the MATLAB command window:

```
Error using imread>get_full_filename (line 567)
File "/home/dominic/CERR/CERR_core/Icons/reset_zoom.gif.gif" does not exist.
Error in imread (line 408)
                fullname = get_full_filename([filename, '.', fmt_s.ext{p}]);
Error in sliceCallBack (line 327)
            [I,map] = imread(fullfile(getCERRPath,'Icons','reset_zoom.gif'),'gif');
Error in CERR (line 118)
                sliceCallBack('init'); 
Error while evaluating UIControl Callback.
```
When I attempt to open an image set that has been imported and saved as a .mat file, I get:

```
Reference to non-existent field 'patientName'.
Error in sliceCallBack (line 517)
        set(stateS.handle.patientName,'string',patName)
Error in sliceCallBack (line 1691)
        sliceCallBack('load'); 
Error while evaluating Menu Callback.
```
The patientname field is definitely there in the original DICOM file.

Any ideas what my problem is? Are there any toolboxes that I need to have installed in order to run CERR? I have the image processing toolbox but otherwise mine is a standard install of MATLAB without bells and whistles.

**Comment by ojalaj** [comment]
@dominicrafferty @adityaapte I have reported the first issue and solution already in #473 - waiting for the fix.

**Comment by adityaapte** [comment]
Just pushed an update as per @ojalaj to handle the .gif filenames. Can you please see if it fixes your issue.

**Comment by dominicrafferty** [comment]
Hello yes this does seem to have solved my issue. It is working now
