### ISSUE TITLE
DICOM conversion

### ISSUE THREAD

**Issue by paulamartingonzalez** [cerr/CERR#494]
When converting a DICOM CT scan to planC, my soft tissues are getting really high values (~2000 HU). They are not present in the DICOM scan when viewed with standard viewers so I assume the issue comes from the conversion. I am using the CERR import button on the GUI and I also tried with the batch convert but the issue persists. Any hint of what might be going on?

**Comment by adityaapte** [comment]
The scanArray stored in planC has an offset to store data as type uint. Subtract the offset as follows to get HUs:

ctOffset = planC{indexS.scan}.scanInfo(1).CTOffset;
scan3M = double(planC{indexS.scan}.scanArray) - ctOffset:
