### ISSUE TITLE
I think I may have noticed a typo in the source code? Would appreciate some input from devs

### ISSUE THREAD

**Issue by sama2689** [cerr/CERR#498]
So I was trying to add doses together using the Add/Subtract/Reassign function and I kept getting the error 

```
Reference to non-existent field 'NumberofFractionsPlanned'.
Error in doseSummationMenu (line 369)
                paramS.numFractions.val = planC{indexS.beams}(planNum).FractionGroupSequence... 
Error while evaluating UIControl Callback.
```

After doing some digging I noticed that the script `doseSummationMenu `is looking for a field called `NumberofFractionsPlanned`, however when I loaded my DICOM data into a .mat file using CERR, CERR called the corresponding field `NumberOfFractionsPlanned` (capital O). Upon capitalizing the O, the summation of doses works again. I am not sure if this is a problem on just my end or with the software so thought I might pass this on to the devs.

Thanks

**Comment by adityaapte** [comment]
The GUI lacked options to specify fractionation vs physical dose summation.
I just pushed updates to handle this. Please pull the latest changes.

Also, it is possible to sum doses in a batch mode. Here is an example with
and without LQ correction:

    global planC % can also be loaded directly from file
    doseNumV = [1, 2]; % sum doses 1 and 2.
    assocScan  = 1; % associate the summed dose with scan 1
    wtfactor = ones(size(doseNumV)); % weighting

    % Physical dose
    newDoseName = 'Sum Physical';
    lqParamS = [];
    planC = sumDose(doseNumV,wtfactor,lqParamS,assocScan,newDoseName,planC);

    % LQ corrected dose
    lqParamS.abRatio = 3;
    lqParamS.stdFractionSize = 2;
    newDoseName = 'Sum LQ';
    planC = sumDose(doseNumV,wtfactor,lqParamS,assocScan,newDoseName,planC);
