### ISSUE TITLE
Heart Segmentation Container request

### ISSUE THREAD

**Issue by trevismd** [cerr/CERR#539]
Hi,
I would very much like to work with the Heart Segmentation Container for research purposes. Could you please provide a download link ?

Thank you !

**Comment by adityaapte** [comment]
Hi Florian, happy to share the container. can you please provide the
following:
1. Name, 2. Institution, 3. Purpose of using the container, 4. email
address to send the Box download link.

Thanks.

**Comment by trevismd** [comment]
I've got it, thanks!
