### ISSUE TITLE
Cardiac Substructures container request

### ISSUE THREAD

**Issue by afg1** [cerr/CERR#552]
Sorry if this isn't the way I'm meant to request access to the containers, but the request submission link sent me here.

I'd like to use the cardiac substructure autosegmentation container in our data at Manchester. We've got singularity installed on a linux machine, we can also handle pytorch if that is easier.

Thanks!

**Comment by adityaapte** [comment]
We will be happy to send the download link for singularity container. Can you please provide
(1) Affiliation, (2) Intended use of the container, (3) Email address to send the Box download link.

**Comment by afg1** [comment]
Hi, 
That's great, thanks!

Affiliation: The University of Manchester, UK
Intended use: Evaluation of cardiac substructure dose in a large retrospective cohort of NSCLC patients
Email address: andrew.green-2@manchester.ac.uk

Thanks again

**Comment by adityaapte** [comment]
Provided access to Conda env. Please refer to the following for usage:
https://github.com/cerr/CERR/wiki/Starting-DL-Segmentation-from-planC
