### ISSUE TITLE
Naming clash with inbuilt function in Matlab 2020b

### ISSUE THREAD

**Issue by pwhybra** [cerr/CERR#574]
I noticed the inbuilt Matlab function _rmfield_ did not work properly once CERR was added to the path in 2020b. This bug **was not** replicated in 2018b. 

Via debug, I found that the CERR function _matches_ clashes with a relatively new inbuilt Matlab function of the same name, causing the error inside _rmfield_ (which has been updated in recent version of Matlab to use _matches_).

Two functions with the same name:

- CERR/CERR_core/Database BETA/matches.m

- https://www.mathworks.com/help/matlab/ref/matches.html

Should this function be renamed to remove this clash? I can add further details if needed. Thank you.

**Comment by adityaapte** [comment]
We plan to remove the "matches" function in the next update. This change is up on the testing branch. Thanks for pointing it out.
