### ISSUE TITLE
DICOM data not Loading

### ISSUE THREAD

**Issue by RahulS-1995** [cerr/CERR#579]
Hi,

I couldn't load the DICOM data. It says no DICOM data. But I can open the DICOM files on slicer and other DICOM viewer. Screenshot Attached.  Thanks in Advance.
![GITHUB issue](https://user-images.githubusercontent.com/65390942/109661011-d0374e00-7b69-11eb-8089-5e040bad826f.JPG)

Best, 
Rahul

**Comment by adityaapte** [comment]
Hi Rahul,

Is your DICOM data under sub-directories? If yes, can you try changing the
following value in CERROptions.json:
"importDICOMsubDirs" : "yes",

-Aditya

**Comment by RahulS-1995** [comment]
Hi Aditya,

I changed value to yes. It gives me the same error. 
When I checked it, it seems that 
org.dcm4che3.io.DicomInputStream(ifile);  throws an exception for my dcm file. Thanking you.

Best,
Rahul Suresh

**Comment by adityaapte** [comment]
Is it possible to share the anonymized dataset?

**Comment by RahulS-1995** [comment]
https://drive.google.com/drive/folders/1XfwKbf-iLC_nhPUVVk-8DKu7Aa9Wdq4V?usp=sharing

**Comment by RahulS-1995** [comment]
The issue is resolved.
