### ISSUE TITLE
Issues after saving a project

### ISSUE THREAD

**Issue by mojtaba1365** [cerr/CERR#589]
I imported around 2000 ct images into the CERR then saved the project. But the size of the saved file turns to 1 KB and by opening the file, I get the error:

Reference to non-existent field 'planC'.
Error in sliceCallBack (line 1619)
        planC           = planC.planC; %Conversion from struct
        created by load 
Error while evaluating Menu Callback.

Any comments?

**Comment by adityaapte** [comment]
Did you import data via script or GUI? Any particular steps to reproduce the behavior?

**Comment by mojtaba1365** [comment]
> Did you import data via script or GUI? Any particular steps to reproduce the behavior?
> […](#)

Via GUI.

Solved...
I found it takes some minutes to save the file because of the high number of images.

And for another issue, after importing the 3ddose file into CERR, I can not see the dose distribution immediately. I have to save, close and reopen the project to see it. 
Any suggestion?
