### ISSUE TITLE
Problem with CERR DICOM import

### ISSUE THREAD

**Issue by ojalaj** [cerr/CERR#591]
I downloaded the latest branch and tried to import a Varian Eclipse TPS exported plan through GUI. After selecting the folder, I got following error:
```
Error: File: scanfile_mldcm.m Line: 52 Column: 20
The input character is not valid in MATLAB statements or expressions.
Error in scandir_mldcm (line 93)
    [attrData, isDcm] = scanfile_mldcm(filename,excludePixelDataFlag);

Error in CERRImportDCM4CHE (line 64)
patient = scandir_mldcm(dirPath, excludePixelDataFlag);

Error in CERR (line 133)
                    CERRImportDCM4CHE;
 
Error while evaluating UIControl Callback
```
However, there were no errors on branch with latest commit on February 26th 2021, so something has changed during past two months.

**Comment by ojalaj** [comment]
Ping @adityaapte on this?

**Comment by adityaapte** [comment]
The line number in your error message suggests CERR failed to create java file object. Can you please check whether there are non asii characters in the filename.

**Comment by ojalaj** [comment]
No non-ASCII characters - only files with name format e.g. "CT.1.2.345.etc.dcm". I'm using Matlab R2015a in Linux 64-bit.

**Comment by ojalaj** [comment]
@adityaapte Thanks for returning back to this - I'll try with other datasets and let you know how it goes.

**Comment by adityaapte** [comment]
Sure, can you please send the email address where I can send the Box link.

**Comment by adityaapte** [comment]
This issue has been fixed now and the update is on github. The issue was
related to import of "empty" DVH matrix.
