### ISSUE TITLE
Error in DICOM import

### ISSUE THREAD

**Issue by md863** [cerr/CERR#612]
I am trying to import DICOM data using Matlab 2020b and I am getting this error below - any suggestion? Thanks!

          _Dot indexing is not supported for variables of this type.
          
          Error in populate_planC_scan_field (line 131)
                              sliceV =
                              cast(imgobj.getInts(2.145386512000000e+09),'int16'); %OW
          
          Error in populate_planC_field (line 83)
                                  populate_planC_scan_field(names{i}, ...
          
          Error in dcmdir2planC (line 53)
              cellData = populate_planC_field(cellNames{i}, dcmdir_PATIENT, optS);
          
          Error in CERRImportDCM4CHE (line 120)
              planC = dcmdir2planC(combinedDcmdirS,mergeScansFlag,optS);
          
          Error in CERR (line 133)
                              CERRImportDCM4CHE;
           
          Error while evaluating UIControl Callback._

**Comment by mhdakheel** [comment]
may I know what did you do to solve this problem?! thanks
