### ISSUE TITLE
Using a DIR registration

### ISSUE THREAD

**Issue by MohHu** [cerr/CERR#625]
Dear developers,

I am a new user to CERR, and I would like to use it for deformable image registration.

My question is that whether this package supports DIR application on two images?

I look forward to hearing from you.

Sincerely

**Comment by adityaapte** [comment]
Here is Wiki documentation on it. I suggest starting by installing
Plastimatch and using CERR's wrapper as described below.
https://github.com/cerr/CERR/wiki/Deformable-Image-Registration-(DIR)

**Comment by MohHu** [comment]
> Dear developers,
> 
> I am a new user to CERR, and I would like to use it for deformable image registration.
> 
> My question is that whether this package supports DIR application on two images?
> 
> I look forward to hearing from you.
> 
> Sincerely

Dear Dr.
