### ISSUE TITLE
Deformable registration with CERR 

### ISSUE THREAD

**Issue by MohHu** [cerr/CERR#639]
Dear developer,

Good afternoon,

I installed Plastimatch using ''Installing the plastimatch windows binary'' as the steps mentioned on ''https://plastimatch.org/windows_installation.html#windows-installation''. 

With regard to running the registration, I have two quesitions:
1- Is Installing the plastimatch windows binary enough for running registration on CERR or I need to Compiling from source?
2- In the code you posted on the link '' https://github.com/cerr/CERR/wiki/Deformable-Image-Registration-(DIR)'', you recommend to set path to tmpDirPath = '/path/to/temp/dir_registration_temp';. so I tried to find in the CERR setting but it is not there. Could you please how I can get dir_registration_temp?

Yours sincerely

**Comment by MohHu** [comment]
Thank you in advance for effort

**Comment by MohHu** [comment]
Dear developer,

Wit regard to above question, I would like to edit other questions.  I n fact, I installed  the plastimatch windows binary and put it in (F:\Plastimatch) directory. Then, since I use Windows 10, I just added directory to the PATH using system variable (F:\Plastimatch\bin), the same thing has been conducted to Matlab (set path, add with subfolders). When I write ''plastimatch'' on command window I have this output 
C:\Users\hp>plastimatch
plastimatch version 1.9.0
Usage: plastimatch command [options]
Commands:
  add           adjust        average       bbox          boundary
  crop          compare       compose       convert       dice
  diff          dmap          dose          drr           dvh
  fdk           fill          filter        gamma         header
  intersect     jacobian      lm-warp       mabs          mask
  maximum       ml-convert    multiply      probe         register
  resample      scale         segment       sift          stats
  synth         synth-vf      threshold     thumbnail     union
  warp          wed           xf-convert    xf-invert.

However, I have done some trials to make sure whether I am on the right track using this code which I have adapted from this link (https://github.com/cerr/CERR/wiki/Deformable-Image-Registration-(DIR)), 
clear
clc
% Load base image as planC
baseCerrFile = 'F:\Plastimatch/ct1.mat';
planC = loadPlanC(baseCerrFile,tempdir);
planC = updatePlanFields(planC);
planC = quality_assure_planC(baseCerrFile,planC);
indexS = planC{end};
 
% Load moving image as planD
movCerrFile = 'F:\Plastimatch/ct.mat';
planD = loadPlanC(movCerrFile,tempdir);
planD = updatePlanFields(planD);
planD = quality_assure_planC(movCerrFile,planD);
indexSD = planD{end};
% NOTE - base and moving images can also be loaded from the same planC, if
% available

% Define registration settings
registration_tool = 'PLASTIMATCH';
plmSettingsFile = '/path/to/plastimatch_registration_settings/plm_reg_settings_with_landmark_stiffness.txt';
baseMask3M = [];
movMask3M = [];
threshold_bone = -800;
inBspFile = '';
outBspFile = '';
tmpDirPath = '/path/to/temp/dir_registration_temp';
algorithm = 'BSPLINE PLASTIMATCH';
% Generate landmarks
baseLandmarkStrC = {'DL_PERICARDIUM'};
movLandmarkStrC = {'DL_PERICARDIUM'};
 
% Register planD to planC
baseScanIndex = 1;
movingScanIndex  = 2;
strBaseC = {planC{indexS.structures}.structureName};
strMovC = {planD{indexSD.structures}.structureName};
landmarkListM = [];
planC = register_scans(planC, baseScanIndex, planD, movingScanIndex,...
    algorithm, registration_tool, tmpDirPath, baseMask3M,...
    movMask3M, threshold_bone, plmSettingsFile, inBspFile,...
    outBspFile, landmarkListM);
planC = register_scans(planC, baseScanIndex, planD, movingScanIndex, algorithm, baseMask3M, movMask3M, threshold_bone);

The out put on command line of MATLAB is 

CERR>>  Loading ct1.mat...
CERR>>  Loaded ct1.mat...
CERR>>  Loading ct.mat...
CERR>>  Loaded ct.mat...
Plastimatch selected
Could not open file: \path\to\temp\dir_registration_temp\baseScan_CT.1.3.46.423632.336926202142184737371.15957.mha
Index exceeds matrix dimensions.

Error in genScanUniqName (line 11)
    scanUID = planC{indexS.scan}(scanNum).scanUID;

Error in register_scans (line 151)
[movScanUniqName, movScanUID] = genScanUniqName(movPlanC,movScanNum);

Error in Untitled (line 39)
planC = register_scans(planC, baseScanIndex, planD, movingScanIndex,...

Could you please tell me how I can overcome this problem?

Yours sincerely

**Comment by adityaapte** [comment]
Hi,

I see that the variables plmSettingsFileand tmpDirPath still point to the
placeholders.These should be updated to reflect the location of your
settings file and directory for temporary i/o between plastimatch and CERR.
You can use settings file from examples provided with CERR:
https://github.com/cerr/CERR/blob/master/CERR_core/ImageRegistration/plastimatch_command/bspline_register_cmd.txt
.

Best,
Aditya

**Comment by MohHu** [comment]
Thank you very much for your efforts!!
plmSettingsFile and tmpDirPath  becomes as below, but there is another error which posted below as well:
plmSettingsFile = 'F:\CERR-master\CERR-master\CERR_core\ImageRegistration\plastimatch_command/bspline_register_cmd.txt';
tmpDirPath = 'C:\Users\hp\AppData\Local\Temp';


CERR>>  Loading ct1.mat...
CERR>>  Loaded ct1.mat...
CERR>>  Loading ct.mat...
CERR>>  Loaded ct.mat...
Plastimatch selected
Index exceeds matrix dimensions.

Error in genScanUniqName (line 11)
    scanUID = planC{indexS.scan}(scanNum).scanUID;

Error in register_scans (line 151)
[movScanUniqName, movScanUID] = genScanUniqName(movPlanC,movScanNum);

Error in Untitled (line 40)
planC = register_scans(planC, baseScanIndex, planD, movingScanIndex,...

**Comment by MohHu** [comment]
Dear Dr. Aditya
With regard to the previous post, I accessed to genScanUniqName and changed scanNum to baseScanNum, but there is popup with this title(''plastimatch.exe'') and text (''A problem caused the program to stop working correctly. Windows will close the program and notify you if a solutiin is available.'')

and comand  Window of matlab has this error:

CERR>>  Loading ct1.mat...
CERR>>  Loaded ct1.mat...
CERR>>  Loading ct.mat...
CERR>>  Loaded ct.mat...
Plastimatch selected
Loading fixed image [0]: C:\\Windows\\Temp\\baseScan_CT.1.3.46.423632.336926202142184737371.15964.mha 
Loading moving image [0]: C:\\Windows\\Temp\\movScan_CT.1.3.12.2.1107.5.1.4.69857.30000021041810281535900062993157.mha 
Couldn't open C:\\Windows\\Temp\\movScan_CT.1.3.12.2.1107.5.1.4.69857.30000021041810281535900062993157.mha for read 
Launching registration worker thread 
Inside registration worker thread 
Unhandled image type (PLM_IMG_TYPE_UNDEFINED) in set_from_plm_image 
Error using fullfile (line 36)
Not enough input arguments.

Error in readPlastimatchCoeffs (line 4)
xformFileName = fullfile(srch.folder,srch.name);

Error in register_scans (line 241)
    algorithmParamsS = readPlastimatchCoeffs(xformFileNameBase);

Error in Registration_by_CERR (line 64)
planC = register_scans(planC, baseScanNum, planD, movScanNum,...

**Comment by adityaapte** [comment]
Can you check the value of movingScanIndex and whether it is available in planD (the moving image). 

Aditya

**Comment by adityaapte** [comment]
The error log says "Couldn't open C:\Windows\Temp\movScan_CT.1.3.12.2.1107.5.1.4.69857.30000021041810281535900062993157.mha for read". It might be that Plastimatch/Matlab has no read permission to this folder. Can you try selecting a different temporary directory that has suitable read/write permissions?

Aditya

**Comment by MohHu** [comment]
Actually, I changed it from C:\Windows\Temp and another to C:\Users\hp\AppData\Local\Temp, but I have the same error.

What I do now is get used to using CERR effectively and understand its potential regarding deformable image registration and how to display deformed scan and structure on CERR GUI. Actually,  (baseScanNum = scanNum;) and ( movScanNum  = scanNum;) are not clear to me what they mean. 

Do you recommend any further source(s) that explains the code posted on ('https://github.com/cerr/CERR/wiki/Deformable-Image-Registration-(DIR)')

I would appreciate your help

**Comment by adityaapte** [comment]
The sample code demonstrates registration between two scans. The base scan is at index baseScanIndex in baseCerrFile and the moving scan is at movScanIndex in movCerrFile. These are two different scan volumes. The DL_PERICARDIUM structure's geometric center can be used as a landmark in addition to bsplines registration cost function. The landmark will be ignored if structures are missing. 

In order to debug the issues you are encountering, I would suggest to look at the generated plastimatch command file     (.txt) and examine the scan volumes in .mha format. Make sure various objects used by the command file are accessible. If you want, please share the images (planC files) you are trying to register and I can suggest some parameters for the command file to get started.

**Comment by MohHu** [comment]
Thank you for your clarification,

ct1 is the base image and ct is the moving image. They in the links below:

https://drive.google.com/file/d/1tcpVekreA2PKteHs3tJnCNOsb8hkYQtW/view?usp=sharing
https://drive.google.com/file/d/1KnQGltHDXN_RfzC1r5H8DhCX4SwwYR5u/view?usp=sharing

Yours sincerely
