### ISSUE TITLE
Deformable registration 

### ISSUE THREAD

**Issue by MohHu** [cerr/CERR#661]
Dear developer(s),

Good morning,
I have been using deformable image registration applied in CERR, and It works and deforms scan from moving image image to base image. What I am working on is that I am trying to applied a  CERR tool for DIR between the base and the moving CT of the patient to generate the displacement vector field (DVF) inside of the OARs on base image. However, when I use the DIR code on this link (''https://github.com/cerr/CERR/wiki/Deformable-Image-Registration-(DIR)''), the scan is deformed, but the structures are not.

I was wondering how I can deform the structure, and how I can extract the DVF for each OARs contour?

Thank you in advance for effort and I appreciate your help and your suggestion!

Yours sincerely

**Comment by MohHu** [comment]
Dear Dr. Aditya,

Sorry for bothering you,

With regard to vector field, after executing the code, I got dvf as 3D .mat file, but there is no indication of the x, y and z components. What I mean in which direction Plastimatch calculates DVF, for instance vector in anterior-posterior (AP) direction, left-right (LR) direction or superior-inferior direction.

Thank you in advance

**Comment by adityaapte** [comment]
The vector field corresponds to CERR image coordinates. x,y,z grid for the
vector field in CERR image coordinates can be obtained as follows:
[xBaseV,yBaseV,zBaseV] = getUniformScanXYZVals(planC{indexS.scan}(scanNum));
[xBase3M,yBase3M,zBase3M] = meshgrid(xBaseV,yBaseV,zBaseV);

**Comment by MohHu** [comment]
Thank you very much

**Comment by MohHu** [comment]
Dear Sir,

Good morning,

I was wondering whether CERR has crop and resample function.

Yours sincerely

**Comment by adityaapte** [comment]
% Crop Scan within the bounding box of strNum
strNum = 1;
scanNum = 1;
margin = 1.5; %cm,
planC = cropScan(scanNum,strNum,margin,planC);

% Resample scan to a new resolution
dx = 0.1; %cm,
dy = 0.1; %cm,
dz = 0.1; %cm,
sinc_flag = 0; % set to 1 to use sinc sampling, 0 for linear interp.
planC = reSliceScan(scanNum,dx,dy,dz,sinc_flag,planC);

In order to create a cubic ROI, type createROI in the CERR command box and
follow the instructions to select bounds on any of the two views.

**Comment by MohHu** [comment]
Thanks a lot for your prompt reply,

Resampling function works, but cropping function causes this following error. Also, when I type createROI in the CERR command box, I have pupup with these three options (''Rectangular''Free-hand''&''cancel''). I chose ''Rectangular'' option, but there is no furhter steps to complete the cropping

Index exceeds matrix dimensions.
Error in getStructureAssociatedScan (line 65)
assocScanUID = allAssocScanUID(structsV);
Error in cropScan (line 66)
assocScanNum = getStructureAssociatedScan(structureNum,planC); 

Do you have a manual on how to conduct cropping?

Yours sincerely

**Comment by adityaapte** [comment]
To create a rectangular ROI, simply draw rectangles on any of the two
views, then right click and hit "Create 3D ROI".

The cropScan function is producing errors since the structure input to it
does not exist.

**Comment by adityaapte** [comment]
Here is the documentation for slice-wise contouring tool:
https://github.com/cerr/CERR/wiki/Contouring-(using-reference-series)

Instructions for createROI command are missing. Would you like to create a
pull request for this documentation? Thanks.

**Comment by MohHu** [comment]
Dear Dr. Aditya,

((''Would you like to create a pull request for this documentation?'') 

I have two sets of images. Each set has different volume from another. I used these sets as an input into image registration code. Before registering them, I would like to crop them and make them of the same volume. 

It is not clear to me how to crop the image. Why t does ''the cropScan function'' requires the structure input because I am working only with scan?


Yours sincerely

**Comment by adityaapte** [comment]
The cropScan function uses structure bounds to crop the image ( with a
margin). So you will need to define a structure on each scan before
cropping.

**Comment by MohHu** [comment]
Thank you very much,

It works, and I got what is required to my work. I have further two questions:
1- I have extracted DVF using the code that you already mentioned, then modified. 
Could you tell me how I could deform the moving image with modified dvf?
2- I used the following code for overriding the density of an organ, then I saved planC from command window. However, when open the saved planC, there is no override structure.
Could I request you how I can over come this problem?

Yours sincerely

global planC;

strNum = 1; %Replace with structure # of interest

%Get associated scan array

scanNum = getStructureAssociatedScan(strNum,planC);

scan3M = getScanArray(scanNum,planC);

%Get structure mask

mask3M = getStrMask(strNum,planC);

%Replace values within mask with assigned densities

%scan3M(mask3M) = density3M(mask3M);
val = 500;

scan3M(mask3M) = val;

**Comment by MohHu** [comment]
Thank you. 

It works, and I got what is required to my work. I have further question:
1- I have extracted DVF using the code that you already mentioned, then modified.

Could you tell me how I could deform the moving image with modified dvf?

Yours sincerely

**Comment by MohHu** [comment]
Dear developer,
Is there any suggestion for last post? I  also have further question to the last post.

 Could you tell me where I can find rigid image registration results (as transformation matrix) from CERR?


Yours sincerely

**Comment by adityaapte** [comment]
The existing wrapper function to create deformed scan/structure/dose works
from bspline coefficients. Here is suggestion to use vector field to warp
image objects:

1> Create a function createMhaVectorFieldFromCERR.m using
createMhaScansFromCERR.m as the template.

2> Use the following transformations to convert from CERR to mha coordinate
system.

vfFileName = 'absolute/path/to/save/vector/field/file';
vf_mha_coords(:,:,:,1) = flipdim(permute(vf(:,:,:,1),[2,1,3]),3)*10;
vf_mha_coords(:,:,:,2) = flipdim(permute(-vf(:,:,:,2),[2,1,3]),3)*10;
vf_mha_coords(:,:,:,3) = flipdim(permute(-vf(:,:,:,3),[2,1,3]),3)*10;

3> Update warp_scan.m etc functions to handle vector field.

**Comment by MohHu** [comment]
Thank you,

1- I found ''createMhaVectorFieldFromCERR.m'' with three arguments which are ''scanNum'', ''scanFileName'' and planC. So, in a new template function do I need leave the same arguments or using deformS as an argument.
2- In warp_scan function, deformS argument is used, but I am dealing with  the vector field corresponds to CERR image coordinates. x,y,z grid. Do you recommend to use deformS?
3-

**Comment by MohHu** [comment]
Dear Dr. adityaapte,

Thank you 
1-''deformS'' was extracted and vector field (vf) was obtained. 
2- The following form was written as:function success = createMhaScansFromCERR(vf)
vfFileName = 'E:/vf.mat';
x_fixed= load('vf.mat');
vf=x_fixed.vf;
vf_mha_coords(:,:,:,1) = flipdim(permute(vf(:,:,:,1),[2,1,3]),3)*10;
vf_mha_coords(:,:,:,2) = flipdim(permute(-vf(:,:,:,2),[2,1,3]),3)*10;
vf_mha_coords(:,:,:,3) = flipdim(permute(-vf(:,:,:,3),[2,1,3]),3)*10;
3- ''warp_scan.m'' was updated by:
replacing   both ''success = createMhaScansFromCERR(movScanNum, movScanFileName, movPlanC)'' and  ''success = createMhaScansFromCERR(refScanNum, refScanFileName, planC)'' by  '' success = createMhaScansFromCERR(vf)''

Could you please tell me whether this function is correct?

Yours sincerely

**Comment by MohHu** [comment]
Dear Dr. adityaapte,

After getting the DVF, I would like to analyze the results by comparing it with another dvf. I understand DVF of another DVF is specified per voxel and the values in DVF are in the unit of voxels, and the positive direction is along how voxel indices increase.

I was wondering whether there is a method that can be used to make matrix of CERR dvf matches another matrix.

Yours sincerely

**Comment by MohHu** [comment]
Dear Dr. adityaapte,

Good morning,

I am working on analyzing the difference between the results of CERR registration and the other registration. Actually, the observation check seems to be alright, but when I try to make quantitative analysis, there is a significant difference between two algorithms, which is not relevant to the real results.  

The second algorithm that I use has this property (''DVF is specified per voxel, rather than using any physical coordinates. While  the positive direction is along how voxel indices increase, the values in DVF are in the unit of voxels''.


Do you mind me asking if it is possible to modify the dvf measured up by CERR to the type mentioned above?


I appreciate your efforts.


Yours sincerely

**Comment by MohHu** [comment]
Dear Sir, 

Happy new year,

Is there any suggestion about the last post, which corresponds to how CERR specify DVF?

Yours sincerely

**Comment by adityaapte** [comment]
According to what you described, the units of DVF resulting from your 2nd
DVF algorithm are in voxels. "DVF is specified per voxel, rather than using
any physical coordinates. While the positive direction is along how voxel
indices increase, the values in DVF are in the unit of voxels."

The DVF calculated in CERR (using plastimatch) is in physical units (cm per
CERR units). So you will have to convert DVFs to the same units. Here is
how you can convert the 2nd DVF to physical units:

global planC
indexS = planC{end};
scanNum = 1;
[xV,yV,zV] = getScanXYZVals(planC{indexS.scan}(scanNum));
dx = abs(xV(1) - xV(2));
dy = abs(yV(1) - yV(2));
dz = abs(zV(1) - zV(2));
xDVF_cm = xDVF_vox * dx;
yDVF_cm = xDVF_vox * dy;
zDVF_cm = xDVF_vox * dz;

-Aditya

**Comment by MohHu** [comment]
Thank you very much,

Actually, one characteristic of CERR registration, Image warping applies 3D geometric transformations on the images to retain
geometric alignment between their features, while color interpolation blends their color.

I traced warp function, but I have not found the function that deals with color blending?

I was wondering how I can inactivate color blending (I need only geometric wrap without color blending).

Yours sincerely

**Comment by MohHu** [comment]
Dear Dr. adityaapte,

Hope you are well

I have two questions I would like to ask about:

- I was wondering whether I could warp the structure without intensity blending, 

- When I applied the hints that you already mentioned with regard to converting image coordinate to physical coordinate, it works and globally the results are fine, but locally there is some differences for local deformation. Actually, DVF specified in image coordinate is that ''the positive direction is along how voxel indices increase''. So, the problem may be due to  the physical coordinate positive direction might not be the same as the voxel index positive direction.

 Is the physical coordinate positive direction of CERR the same as the voxel index positive direction?

Yours sincerely

**Comment by MohHu** [comment]
Dear Sir,

Good afternoon,

Is there any suggestions regarding previous post?

Yours sincerely

**Comment by MohHu** [comment]
Dear Sir,

Good afternoon,

Is there any suggestions regarding previous post?

Yours sincerely

**Comment by adityaapte** [comment]
Hi, I am not quite sure what you mean by color blending. The deformable
registration uses b-splines registration which can use MSE or MI metric.
There are functions to deform scan, structure and dose based on the
b-splines coefficients - warp_scan.m, warp_structures.m and warp_dose.m
respectively. Can you perhaps post some images to give us more information?

**Comment by MohHu** [comment]
Thank you very much for your kind reply,

Actually, I have two problems.
A- I am comparing two registration algorithms one is by CERR, and another one is by another software. The information of another one are that:
1- DVF is specified in the unit of voxels. This one has been solved 
 2- The positive direction is along how voxel indices increase. So, ''I would like to make sure whether the physical coordinate positive direction of CERR is the same as the voxel index positive direction''

B-Yes, It is now clear to me. Actually, I would like to use the function that deforms the scan. I used ''warp_scan'' as in the code below but I have this error 
(Undefined function or variable 'vf'.
Error in warp_scan (line 43)
success = createMhaScansFromCERR(vf);
Error in Registration (line 106)
  Deformed_scan = warp_scan(deformS,movScanNum,movPlanC,planC,tmpDirPath,interpolation,inverseFlag) 
>> )

clear; clc
% Filename of base scan
baseCerrFile = 'F:\Results\Patient_2\Sampled_CBCT.mat';

% Filename of moving scan
movCerrFile = 'F:\Results\Patient_2\Sampled_CT.mat';

% Filename to save registered images
registeredFileName = 'F:\X_Y_Z_Components\Patient_two.mat';

% Plastimatch settings file
plmSettingsFile = fullfile(getCERRPath,'ImageRegistration',...
    'plastimatch_command','bspline_register_cmd_dir.txt');

% temporary directory for cerr/plastimatch i/o
tmpDirPath = 'C:\Users\hp\AppData\Local\Temp';
%tmpDirPath = 'C:\Windows\Temp\';
%C:\Windows\Temp

% index of scan to be used in base and moving planC's
baseScanNum = 1;
movScanNum = 1;
% Define structures to deform from moving to base scan
strsToDeformC = {'Warped_Femoral L','Warped_Femoral R','Warped_Bladder','Warped_Rectum',};
strCreationScanNum = baseScanNum;

% Load base image as planC
planC = loadPlanC(baseCerrFile,tempdir);
planC = updatePlanFields(planC);
planC = quality_assure_planC(baseCerrFile,planC);
indexS = planC{end};
 
% Load moving image as planD
planD = loadPlanC(movCerrFile,tempdir);
planD = updatePlanFields(planD);
planD = quality_assure_planC(movCerrFile,planD);
indexSD = planD{end};
 
% NOTE - base and moving images can also be loaded from the same planC, if
% available

% Define registration settings
registration_tool = 'PLASTIMATCH';
baseMask3M = [];
movMask3M = [];
threshold_bone = -800;
inBspFile = '';
outBspFile = '';
algorithm = 'BSPLINE PLASTIMATCH';
 
% Generate landmarks
baseLandmarkStrC = {''};
movLandmarkStrC = {''};

% Register planD to planC
strBaseC = {planC{indexS.structures}.structureName};
strMovC = {planD{indexSD.structures}.structureName};
landmarkListM = [];
for iStr = 1:length(baseLandmarkStrC)
    baseLandmarkStr = baseLandmarkStrC{iStr};
    movLandmarkStr = movLandmarkStrC{iStr};
    strIndV = getMatchingIndex(baseLandmarkStr,strBaseC,'exact');
    assocScanNumV = getStructureAssociatedScan(strIndV,planC);
    baseLandmarkInd = strIndV(assocScanNumV == baseScanNum);
    strIndV = getMatchingIndex(movLandmarkStr,strMovC,'exact');
    assocScanNumV = getStructureAssociatedScan(strIndV,planD);
    movLandmarkInd = strIndV(assocScanNumV == movScanNum);
    if length(baseLandmarkInd) ~= 1 || length(movLandmarkInd) ~= 1
        continue;
    end
    [baseX,baseY,baseZ] = calcIsocenter(baseLandmarkInd,'COM',planC);
    [movX,movY,movZ] = calcIsocenter(movLandmarkInd,'COM',planD);
    [xBaseV,yBaseV,zBaseV] = getScanXYZVals(planC{indexS.scan}(baseScanNum));
    [xMovV,yMovV,zMovV] = getScanXYZVals(planD{indexSD.scan}(movScanNum));
    baseY = - baseY;
    movY = - movY;
    landmarkListM(iStr,:,1) = [iStr-1, [-baseX,-baseY,-baseZ]*10];
    landmarkListM(iStr,:,2) = [iStr-1, [-movX,-movY,-movZ]*10];
end
 
% Invoke Registration
planC = register_scans(planC, baseScanNum, planD, movScanNum,...
    algorithm, registration_tool, tmpDirPath, baseMask3M,...
    movMask3M, threshold_bone, plmSettingsFile, inBspFile,...
    outBspFile, landmarkListM);
% Warp structures from moving to the base scan (Note that scan is warped in register_scans.m
 
% Access the resulting defomration
deformS = planC{indexS.deform}(end);
     vf = get_vector_field(deformS,planD,movScanNum,planC,baseScanNum);
     vf = squeeze(vf(:,:,:));

% Get matching indices for structures to deform
movStructNumsV = [];
strNamC = {planD{indexSD.structures}.structureName};
for iStr = 1:length(strsToDeformC)
    movStructNumsV = [movStructNumsV,...
        getMatchingIndex(strsToDeformC{iStr},strNamC,'exact')];
end
 
% Invoke function to warp structures
 planC = warp_structures(deformS,strCreationScanNum,movStructNumsV,planD,planC,tmpDirPath);
 interpolation = '';
     inverseFlag =  ' ' ;
  movPlanC = planD
  Deformed_scan = warp_scan(deformS,movScanNum,movPlanC,planC,tmpDirPath,interpolation,inverseFlag)
% Save planC
planC = save_planC(planC,[],'passed',registeredFileName);

**Comment by MohHu** [comment]
Dear Dr. Aditya,

Wit regard to your last post, I managed to run ''warp_scan function'', and the output has just been sent to you.

Yours sincerely

**Comment by MohHu** [comment]
> Dear developer(s),
> 
> Good morning, I have been using deformable image registration applied in CERR, and It works and deforms scan from moving image image to base image. What I am working on is that I am trying to applied a CERR tool for DIR between the base and the moving CT of the patient to generate the displacement vector field (DVF) inside of the OARs on base image. However, when I use the DIR code on this link (''https://github.com/cerr/CERR/wiki/Deformable-Image-Registration-(DIR)''), the scan is deformed, but the structures are not.
> 
> I was wondering how I can deform the structure, and how I can extract the DVF for each OARs contour?
> 
> Thank you in advance for effort and I appreciate your help and your suggestion!
> 
> Yours sincerely
