### ISSUE TITLE
PETSTEP in CERR

### ISSUE THREAD

**Issue by mele-y** [cerr/CERR#678]
hi, I am trying to use [PETSTEP](https://github.com/CRossSchmidtlein/PETSTEP) which is a plugin for CERR,but I am  confued on how to integrate PETSTEP into CERR

**Comment by adityaapte** [comment]
PETSTEP uses CERR's planC data structure. So you will have to download CERR
from https://github.com/cerr/CERR and have both CERR and PETSTEP on the
MATLAB path. You should then be able to use PETSTEP functions such as
PETSim_GUI.

-Aditya

**Comment by mele-y** [comment]
thanks
