### ISSUE TITLE
calc_surfDice_addPathLen.m units of measurements

### ISSUE THREAD

**Issue by sterparia** [cerr/CERR#681]
Hi Aditya,

Just writing to ask about the following matlab script, calc_surfDice_addPathLen.m

Thank you for this, it's really helpful! I just wanted to ask, what unit is the margin and added path length in? Is it in cm or mm?

Thank you
Samsara

**Comment by adityaapte** [comment]
Here is the documentation on metrics to evaluate segmentation.

https://github.com/cerr/CERR/wiki/Segmentation-evaluation-metrics



calc_surfDice_addPathLen.m uses image based discretization for computing
surface dice and APL whereas calcSurfaceDice.m uses a more accurate polygon
representation for such computation. We are currently working on updating
the APL calculation to use a more accurate polygonal discretization.

**Comment by sterparia** [comment]
Ah ok. Thank you for this!
