### ISSUE TITLE
Error in importing MR images

### ISSUE THREAD

**Issue by FoggyJoker** [cerr/CERR#691]
Dear developer,

Thank you for providing a great platform for research, I am currently learning CERR.

Recently, I encountered issues when trying to import MR images in DICOM format, acquired with a Philips Ingenia 3T scanner. Below are the error messages popped during import:

> Error using reshape
> Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for that dimension.
> Error in populate_planC_scan_field (line 367)
>                 dataS = reshape(sliceV, [nCols nRows numMultiFrameImages]);
> Error in populate_planC_field (line 83)
>                         populate_planC_scan_field(names{i}, ...
> Error in dcmdir2planC (line 53)
>     cellData = populate_planC_field(cellNames{i}, dcmdir_PATIENT, optS);
> Error in CERRImportDCM4CHE (line 120)
>     planC = dcmdir2planC(combinedDcmdirS,mergeScansFlag,optS);
> Error in CERR (line 133)
>                     CERRImportDCM4CHE; 
> Error while evaluating UIControl Callback.

I use the latest CERR code and MATLAB 2021b. Based on my experience, the import module works fine for MR images from Siemens, but not as well for Philips. Please share some thoughts when you have time to look into this problem.

Thanks in advance.
Jimmy

**Comment by adityaapte** [comment]
Can you please check whether the dicom directory contains images other than
the 3d volume. I have previously encountered this error when there were,
for example, screenshots mixed with the image slices for 3d volume.

**Comment by FoggyJoker** [comment]
Hi Aditya,
I followed your advice and it worked! The vendor did leave a non-image dicom file in the folder, which probably caused the error.

Really appreciate your help!

Jimmy
