### ISSUE TITLE
Error importing DICOMs

### ISSUE THREAD

**Issue by owenmacl** [cerr/CERR#809]
Hello,

I am trying to import a DICOM set to CERR and cannot seem to get it to work for exports from Oncentra Brachy, but it does work for external beam plans exported from Varian Eclipse, and a low dose rate plan from Variseed. I am wondering is this a known issue?

I have put the error message below. I have searched for previous instances of this message being reported, I can confirm the file path does not have any whitespace. And I have tried the latest version of CERR, downloaded on 9/12/22.

Any help would be much appreciated.
Thanks!

Reading directory:C:\Users\User1\Desktop\HDR Prostate ...
 Reading header... 
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.sponsorID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.protocolID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.subjectID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.submissionID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.timeSaved field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.lastSavedInVer field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.CERRImportVersion field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.anonymizedID field, leaving empty.
 Reading comment... 
 Reading scan... 
Loading Scan ...
Array indices must be positive integers or logical values.

Error in populate_planC_field (line 139)
            scanOriS(scansAdded).scanUID = dataS(scansAdded).scanUID;

Error in dcmdir2planC (line 53)
    cellData = populate_planC_field(cellNames{i}, dcmdir_PATIENT, optS);

Error in CERRImportDCM4CHE (line 120)
    planC = dcmdir2planC(combinedDcmdirS,mergeScansFlag,optS);

Error in CERR (line 133)
                    CERRImportDCM4CHE;
 
Error while evaluating UIControl Callback.

**Comment by owenmacl** [comment]
Hello,

Yes, I have tried removing anything unrelated, leaving only the DICOMs (including RTPlan, RTStruct and RTDose).

Sorry I should have mentioned trying this.

**Comment by adityaapte** [comment]
Is it possible to share the anonymized dataset?

**Comment by owenmacl** [comment]
I should be able to generate a dataset on some phantom images. I will get back to you next week with something.

Thanks for the help, I will be in contact.

**Comment by owenmacl** [comment]
Hello,

I have emailed with plans uploaded to OneDrive and shared the links via email.

Thanks!

**Comment by owenmacl** [comment]
This was resolved by verifying the JAVA_HOME environment variable pointed to the correct directory.

Thank you Aditya for all your help in resolving this.
