### ISSUE TITLE
Can I change the doseArray in the planC

### ISSUE THREAD

**Issue by mhdakheel** [cerr/CERR#907]
I have edit the doseArray in a file that I created in the workspace. However, when I tried to convert the file to dicom file and open it in CERR it shows issues like this 
Unrecognized function or variable 'SERIES'.

Error in populate_planC_scan_field (line 54)
        nImages = length(SERIES.Data);

Error in populate_planC_field (line 83)
                        populate_planC_scan_field(names{i}, ...

Error in dcmdir2planC (line 53)
    cellData = populate_planC_field(cellNames{i}, dcmdir_PATIENT, optS);

Error in CERRImportDCM4CHE (line 120)
    planC = dcmdir2planC(combinedDcmdirS,mergeScansFlag,optS);

Error in CERR (line 133)
                    CERRImportDCM4CHE;
 
Error while evaluating UIControl Callback.

The question is can I somehow replace the doseArray from planC data without taking convert my file to dicom and then open it with CERR and if not, can you explain what should I do with this error...Thank you

**Comment by adityaapte** [comment]
Here is code snippet to add 3D doseArray back to planC as a new entry under
planC{index.dose}

% newDoseArray3M; % doseArray modified from doseNum
global planC
indexS = planC{end};
doseNum = 1; % index of dose from which the new doseArray is derived
assocScanNum = getDoseAssociatedScan(doseNum, planC);
assocScanUID = planC{indexS.scan}(assocScanNum).scanUID ;
zV = planC{idexS.dose}(doseNum).zValues;
regParamsS.horizontalGridInterval =
planC{indexS.dose}(doseNum).horizontalGridInterval;
regParamsS.verticalGridInterval   =
planC{indexS.dose}(doseNum).verticalGridInterval;
regParamsS.coord1OFFirstPoint   =
planC{indexS.dose}(doseNum).coord1OFFirstPoint;
regParamsS.coord2OFFirstPoint   =
planC{indexS.dose}(doseNum).coord2OFFirstPoint;
regParamsS.zValues  = zV;
regParamsS.doseUnits = 'GRAYS';
regParamsS.dateWritten = date;
planC = dose2CERR(newDoseArray3M,[],
'NewDose','test','test','non-CT',regParamsS,'no',assocScanUID);

**Comment by mhdakheel** [comment]
Thank you so much...I've been working on this 4 days just to know how to add the new doseArray...It’s been added to CERR (Dose). However, I still cannot see it on the phantom (I mean I have tried  to put the new dose in the phantom and I got this error)

Error while evaluating Menu Callback.

Requested array exceeds the maximum possible variable size.

Error in CERRColorBar (line 151)
        tickV = [0:-deltaTick:colorbarFrameMin deltaTick:deltaTick:colorbarFrameMax];

Error in CERRColorBar (line 65)
        CERRColorBar('INIT_HANDLES', hAxis);

Error in CERRRefresh (line 107)
        CERRColorBar('init', stateS.handle.doseColorbar.trans);

Error in sliceCallBack (line 3594)
        CERRRefresh

Related documentation
 
Error while evaluating Menu Callback.

**Comment by adityaapte** [comment]
Can you save planC to file, then close and open the viewer and load the
saved file? Use the following command to save planC to file:
planC = save_planC(planC,[],'passed','/path/to/save/planCFileName.mat');

**Comment by adityaapte** [comment]
change /path/to/save/planCFileName.mat to the location where you want to
save this file.

**Comment by mhdakheel** [comment]
Grand!! I did save it and re-open it but still same issue no dose appears on the phantom (but when I go to dose management I see the dose and its distribution but on phantom there is nothing!!


Related documentation
 
Error while evaluating Figure WindowScrollWheelFcn.

Requested array exceeds the maximum possible variable size.

Error in CERRColorBar (line 151)
        tickV = [0:-deltaTick:colorbarFrameMin deltaTick:deltaTick:colorbarFrameMax];

Error in CERRColorBar (line 65)
        CERRColorBar('INIT_HANDLES', hAxis);

Error in CERRRefresh (line 107)
        CERRColorBar('init', stateS.handle.doseColorbar.trans);

Error in sliceCallBack (line 3594)
        CERRRefresh

Related documentation
 
Error while evaluating Menu Callback.

**Comment by mhdakheel** [comment]
I think the problem that I'm facing is the size of the array and the (bytes) so whenever I change the class from single to = unit16 the dose changes and becomes so high, however, the bytes become less for example before I change the 'class' (from single to unit16) the bytes =262144 but after I changed it the bytes = 131072 and it appears in the phantom but with a very high dose...the question is how can I change the size of the bytes but without playing with dose and make it significantly high...?!

**Comment by adityaapte** [comment]
Why do you need it to be uint16? doseArray in planC is of data type single.

**Comment by mhdakheel** [comment]
the file size is large and I have to reduce the bytes whenever I change the class from single to unit16 the file works but with very high dose...So now I am trying to use sparse to minimize the bytes size

**Comment by mhdakheel** [comment]
is there a way to reduce the MB with out changing the dose?!

**Comment by adityaapte** [comment]
planC file can be zipped while saving. Or you can downsample the dose
matrix. What's the size of the dose matrix?

**Comment by mhdakheel** [comment]
[128,128,4]

**Comment by adityaapte** [comment]
It's fairly small size. Is there a reason to not save doseAreay as "single"
data type?

**Comment by mhdakheel** [comment]
it's saved as single...
but still I get this 
Related documentation

Error while evaluating Figure WindowScrollWheelFcn.

Requested array exceeds the maximum possible variable size.

Error in CERRColorBar (line 151)
tickV = [0:-deltaTick:colorbarFrameMin deltaTick:deltaTick:colorbarFrameMax];

Error in CERRColorBar (line 65)
CERRColorBar('INIT_HANDLES', hAxis);

Error in CERRRefresh (line 107)
CERRColorBar('init', stateS.handle.doseColorbar.trans);

Error in sliceCallBack (line 3594)
CERRRefresh

Related documentation

Error while evaluating Menu Callback.

**Comment by adityaapte** [comment]
Can you check the min, max values of new doseArray. Looks like there is inf
or -inf?

**Comment by mhdakheel** [comment]
I've checked that in the dose management, and yes the max dose is inf. I tried to make it 83 Gy but the dose distribution becomes cyan with a black hole (i.e. the max dose region )

**Comment by mhdakheel** [comment]
finally, I have done this...Thank you so much for your priceless help

**Comment by mhdakheel** [comment]
finally, I have done this...Thank you so much for your priceless help
