### ISSUE TITLE
request for Deep learning segmentation pre-trained models

### ISSUE THREAD

**Issue by myk-Tomiyama** [cerr/CERR#913]
Hi.
I'm a radiologist and also a Ph.D student at the Department of Artificial Intelligence Diagnostic Radiology at the Graduate School of Medicine / Faculty of Medicine, Osaka university (https://www.med.osaka-u.ac.jp/eng/introduction/research/joint/artificial-intelligence-diagnostic-radiology) in Japan. 
We are a planning on a new research project that requires segmenting heart structures from CT images. 
Can you give us permission to access to your pre-trained models and containers? 
Our project will be purely academic and no commercial use of your asset is planned.

**Comment by adityaapte** [comment]
Sure, can you please let me know your email address so I can add you to our
Box folder? I will share Singularity containers for heart sub structure and
thoracic OAR segmentation.

**Comment by myk-Tomiyama** [comment]
Thank you for contacting me. 
My email address is "m-tomiyama@radiol.med.osaka-u.ac.jp". 
I appreciate your sharing of the Singularity containers for heart substructure and thoracic OAR segmentation.
