### ISSUE TITLE
Local-level dose metrics 

### ISSUE THREAD

**Issue by MohHu** [cerr/CERR#990]
Dear Sir or Madam,

Good morning,

I have two plans of the same region. In addition to DVH and gamma index, I would like to compare local-level dose metrics.

Do you mind me asking how I can use CERR to compare local-level dose metrics of these plans?

Yours sincerely

**Comment by adityaapte** [comment]
You can use the Dose --> Add/Subtract/Reassign tool to subtract the two
doses and compute various metrics (statistical and histogram based).

**Comment by adityaapte** [comment]
1> Uncheck LQ.
2> Select the dose from scan 1 and scan 2.
3> Use a Weighting factor of 1 for one of the doses and -1 for the other
dose.

**Comment by MohHu** [comment]
Thank you for response,

- The error has been solved, but what is the output ? how can I get the results (metrics)?
